twitter:
  consumer_key: XXXXXXXXXXXXXXXXXXXXX
  consumer_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  access_token: XXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  access_token_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
logger:
  shift_age: weekly
search_queries:
  - なぜ俺は
ng_words:
  - '@'
  - RT
ng_clients:
  - twittbot.net
ng_users:
  - 9669669660
  - Best_Teacher132
  - EB6940Orchid
  - JR_Yamanoteline
  - JeremyBenmoussa
  - LLHG_24
  - MyFriendsFollow
  - SOS_hisaisya
  - TFTjp
  - WWWHUKKINWWW
  - affiliate_tora
  - auction_as4
  - cry_hisaisya
  - diet_cafe
  - esaseruyone
  - gorousan3z
  - haneda_otoku
  - helpfive2011
  - igoospce
  - ishiki_hikuiyo
  - kenyblack_nt
  - kickabout28
  - meigenbot
  - mirRoRplacement
  - mirions777
  - nao_kohi821
  - niyaniya__bot
  - omoboibotbot
  - owarai4
  - pansutodaisuki
  - pskinshicho
  - sheikhakbar
  - shopsearch_kun
  - tweet_omosiro
  - twi_tenkomori
  - washozon
  - wwwwww_bot
allow_urls: false
