twitter:
  consumer_key: XXXXXXXXXXXXXXXXXXXXX
  consumer_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  access_token: XXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  access_token_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
logger:
  shift_age: weekly
search_queries:
  - なぜ俺は
ng_words:
  - '@'
  - RT
ng_clients:
  - twittbot.net
ng_users:
  - Best_Teacher132
  - bokete_kings
  - gorousan3z
  - meigenbot
  - niyaniya__bot
  - owarai4
  - punpun_gazou
  - WWWHUKKINWWW
